modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Libre-Computers/LibreComponents/issues"
license = "MIT"

[[mods]]
modId = "librecomponents"
version = "${file.jarVersion}"
displayName = "Libre Components"
authors = "The Realm 18 Studios"
description = '''
Libre Drives all the extra components you need.
'''

[[dependencies.librecomponents]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.librecomponents]]
modId = "minecraft"
mandatory = true
versionRange = "1.19.2"
ordering = "NONE"
side = "BOTH"
[[dependencies.librecomponents]]
modId = "oc2"
mandatory = false
versionRange = "[1.1.0,)"
side = "BOTH"
ordering = "AFTER"
