modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/fnuecke/oc2r/issues"
license = "MIT"

[[mods]]
modId = "librecomponents"
version = "${file.jarVersion}"
displayName = "Libre Components"
authors = "The Realm 18 Studios"
description = '''
Libre Drives all the extra components you need.
'''

[[dependencies.librecomponents]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.librecomponents]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"
[[dependencies.librecomponents]]
modId = "oc2r"
mandatory = false
versionRange = "[1.1.0,)"
side = "BOTH"
ordering = "AFTER"
[[dependencies.librecomponents]]
modId = "libracomputing"
mandatory = false
versionRange = "[0,)"
side = "BOTH"
ordering = "AFTER"
